steps:
  - name: node:18
    entrypoint: bash
    dir: "client"
    args:
      - "-c"
      - |
        npm install
        npm run build

  - name: gcr.io/cloud-builders/gcloud
    args:
      [
        "run",
        "deploy",
        "frontend-service",
        "--source=client/build",
        "--region=us-central1",
        "--platform=managed",
        "--allow-unauthenticated"
      ]

options:
  logging: CLOUD_LOGGING_ONLY
