steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/github.com/siblinggrief/sibling-grief:$SHORT_SHA', '.']
    dir: server

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/github.com/siblinggrief/sibling-grief:$SHORT_SHA']
    dir: server

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - backend
      - --image=gcr.io/$PROJECT_ID/github.com/siblinggrief/sibling-grief:$SHORT_SHA
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY
